config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :closes, only: [:index, :show, :create, :new]
  resources :lists, only: [:new, :create]

  get 'closes/index'
  root to: "closes#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/close.rb
class Close < ApplicationRecord
  belongs_to :user
  belongs_to :list, optional: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :users, through: :closes
  has_many :closes
  validates :check_list, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :store_name, presence: true
  has_many :closes
  has_many :lists, through: :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configre_permitted_parameters, if: :devise_controller?

  private
  def configre_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:store_name])
  end
end

app/controllers/closes_controller.rb
class ClosesController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_list, only: [:index, :show, :create]
 
  def index
    @closes = Close.new
  end
 
  def show
    @close = Close.order("created_at desc").limit(100)
  end

  def create
    @closes = Close.new(close_params)
    if  
      @closes.save
      redirect_to root_path
    else
      flash.now
      render :index
    end
  end
 
  def set_list
    @list = List.order("created_at desc").limit(1)
  end

 private
 def close_params
  params.permit(:number_of_people).merge(user_id: current_user.id)
 end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @list = List.order("created_at desc").limit(1)
    @lists = List.new
  end

  def create
    @lists = List.new(list_params)
    if 
      @lists.valid?
      @lists.save
      redirect_to root_path
    else
      flash.now
      render :new
    end
  end
  
  private
  def list_params
    params.permit(:check_list).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closes_helper.rb
module ClosesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/closes/_header.html.erb
<div class = "header">
  <div class = "wrapper">
    <div class = "side-bar-header">
      <div class = "heder-name">
        <% if user_signed_in? %>
          <%= link_to current_user.store_name, root_path,  class: "user-nickname" %>
        <%else%>
          <%= link_to "ようこそゲストさん！", root_path, class: "user-nickname" %>
        <%end%>
      </div>  
    </div>
      <div class = "check-header">
          <div class = "left-header">
            <div class = "header-title">
              closed-app
            </div>
          </div>
          <% if user_signed_in? %>
          <div class = "right-header">
            <div class = "header-button">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </div>
          </div>
          <%else%>
          <div class = "right-header">
            <div class = "header-button">
              <%= link_to "ログイン", new_user_session_path%>
              <%= link_to "新規登録", new_user_registration_path%>
            </div>
          </div>
          <%end%>
      </div>
  </div>
</div>

app/views/closes/_log.html.erb
<div class = "check-main">
  <div class = "check-mains">
    <div class = "log-button">
      <%= link_to "もどる",  root_path %>
    </div>
    <div class = "log-title">
      閉店チェックした日付
    </div>
  </div>
  <% if user_signed_in?%> 
  <% @close.where(user_id: current_user.id).each do |close| %>
 <div class = "logtexts">
    <div class = "logtext">
      <%= close.number_of_people%>人で<%= close.created_at.strftime("%m月%d日")%>閉店しました！
         <%end%>
        <%end%> 
       <%if @close.nil?%>
         (例)2020/10/19閉店しました！
        <%end %> 
    </div>
  </div>
  

app/views/closes/_main.html.erb
<div class = "check-main">
  <div class = "check-mains">
    <div class = "log-button">
      <% if user_signed_in? %>
        <%= link_to "ログを参照する", close_path(current_user.id) %>
      <%else%>
        <%= link_to "ログを参照する", "#" %>
      <%end%>
    </div>
    今日の閉店人数
      <% if user_signed_in? %>
    <div class = "buttonspace">
    <div class = "kaigyou">
      <div class = "peoplebutton-block">
      <%= submit_tag"1人 ", class: "peoplebutton", id: "people_1_button"%>
      </div>
      <div class = "peoplebutton-block">
      <%= submit_tag"2人 ", class: "peoplebutton", id: "people_2_button"%>
      </div>
       <div class = "peoplebutton-block">
      <%= submit_tag"3人 ", class: "peoplebutton", id: "people_3_button"%>
      </div>
       <div class = "peoplebutton-block">
      <%= submit_tag"4人 ", class: "peoplebutton", id: "people_4_button"%>
      </div>
       <div class = "peoplebutton-block">
      <%= submit_tag"5人  ", class: "peoplebutton", id: "people_5_button"%>
      </div>
      </div>
      <div class = "kaigyou">
       <div class = "peoplebutton-block">
      <%= submit_tag"6人 ", class: "peoplebutton", id: "people_6_button"%>
      </div>
       <div class = "peoplebutton-block">
      <%= submit_tag"7人 ", class: "peoplebutton", id: "people_7_button"%>
      </div>
       <div class = "peoplebutton-block">
      <%= submit_tag"8人 ", class: "peoplebutton", id: "people_8_button"%>
      </div>
       <div class = "peoplebutton-block">
      <%= submit_tag"9人 ", class: "peoplebutton", id: "people_9_button"%>
      </div>
      <div class = "peoplebutton-block">
      <%= submit_tag"10人", class: "peoplebutton", id: "people_10_button"%>
      </div>
      </div>
    </div>
  </div>
  
    <div class = "block">
      <h2 class = "peoplemaru" id = "peoplemaru_1"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_2"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_3"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_4"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_5"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_6"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_7"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_8"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_9"></h2>
      <h2 class = "peoplemaru" id = "peoplemaru_10"></h2>
    </div>

    <div class = "block">
    <div class = "kaigyoumarubatu">
      <h2 class = "marubatubuttonok" id = "buttun1ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun1ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun2ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun2ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun3ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun3ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun4ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun4ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun5ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun5ng"></h2>
      </div>
    <div class = "kaigyoumarubatu">
      <h2 class = "marubatubuttonok" id = "buttun6ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun6ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun7ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun7ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun8ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun8ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun9ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun9ng"></h2>
      <h2 class = "marubatubuttonok" id = "buttun10ok"></h2>
      <h2 class = "marubatubuttonng" id = "buttun10ng"></h2>
      </div>
    </div>

   <div class = "form">
    <%= form_with model:@closes, url:closes_path, method: :post, class:"check-form", id: "check-form", local: true do |f|%>
          <%= text_field_tag(:number_of_people,"4", class: "check-text", id: "check-text")%>    
           <%= submit_tag"ログ投稿", class: "check-submit", id: "check-submit"%>
    <%end%>
    <%else%>
    ログインしたら、チェック、ログ参照ができるようになります！
    <%end%>
</div>
</div>

app/views/closes/_side_bar.html.erb
<div class = "side-bar-main">
  <div class = "side-bar-mains">
    <div class = "check-list-title">
      チェックリスト
    </div>
     <%if user_signed_in?%>
    <div class = "edit-check-list">
      <%= link_to "チェックリストを編集する", new_list_path %>
    </div>
     <%end%> 
    <div class = "check-list">
      <h2 class = "name">
       <%if user_signed_in?%>
         <%if @list.present?%>
         <%@list.where(user_id: current_user.id).each do |list| %>
             <%=list.check_list%>
        <%end%> 
        <%end%> 
        <%end%> 
        <%if @list.nil?%>
          ウォッシャー電源止めて水抜いた<br>食材期限確認した<br>フライヤー電源止めた<br>炊飯器洗った
        <%end%> 
      </h2>
   </div>
  </div>
</div>

app/views/closes/edit.html.erb
<div class = "header">
  <%= render "header" %>
</div>
<div class = "wrapper">
  <div class = "side-bar">
    <%= render "side_bar" %>
  </div>
  <div class = "edit">
    <%= render "edit" %>
  </div>
</div>

app/views/closes/index.html.erb
<div class = "header">
  <%= render "header" %>
</div>
<div class = "wrapper">
  <div class = "side-bar">
    <%= render "side_bar" %>
  </div>
  <div class = "main-new-set">
  <div class = "main">
    <%= render "main" %>
  </div>
  </div>
</div>

app/views/closes/new.html.erb
<div class = "header">
  <%= render "header" %>
</div>
<div class = "wrapper">
  <div class = "side-bar">
    <%= render "side_bar" %>
  </div>
  <div class = "new">
    <%= render "new" %>
  </div>
</div>

app/views/closes/show.html.erb
<div class = "header">
  <%= render "header" %>
</div>
<div class = "wrapper">
  <div class = "side-bar">
    <%= render "side_bar" %>
  </div>
  <div class = "log">
    <%= render "log" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClosedApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_new.html.erb
<div class = "check-main">
   <div class = "check-mains">
        <div class = "log-button">
          <%= link_to "もどる", closes_path%>
        </div>
        <div class = "log-title">
          チェックリストの編集
        </div>
   </div>
    <%= form_with model: [@lists], url:  lists_path, method: :post,  local: true do |f|%>
     <%= render  "lists/shared/error_messages", model: f.object  %>
      <div class = "edittexts">
        <div class = "text-area-input">
          <%=text_area_tag(:check_list,"（例）ウォッシャー電源切った",size: "30x20",class: "check_list")%>
        </div>
        <div class = "button">
           <%= submit_tag "編集", class: "edit_button" %>
       </div>
      </div>
    <%end%>
</div>

app/views/lists/new.html.erb
<div class = "header">
  <%= render "closes/header" %>
</div>
<div class = "wrapper">
  <div class = "side-bar">
    <%= render "closes/side_bar" %>
  </div>
  <div class = "new">
    <%= render "new" %>
  </div>
</div>

app/views/lists/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>